In [56]:
import pandas as pd
import numpy as np
import os
def storck_handler(stock):
    diff = np.diff(stock.to_numpy(),1)
    diff = diff[diff>0].sum()
    return stock.to_numpy()[0]  + diff

In [61]:
mapping = pd.read_excel("AllDistCenterProvince.xlsx")
stock = []
for path in os.listdir("stock"):
    df = pd.read_excel(f"stock/{path}")
    stock.append(df)
stock = pd.concat(stock,axis=0)
stock.rename(columns={"distcenternew":"DistributionCenter"},inplace=True)
dm = stock.merge(mapping, on=["Distributor","DistributionCenter"])

dm = dm.groupby(["Line","Month","ProductNameEng","Province","day"]).agg({"StockVolume":sum}).reset_index()
dm =  dm.groupby(["Line","Month","ProductNameEng","Province"]).agg({"StockVolume":storck_handler}).reset_index()
# dm.to_excel("stock_sale.xlsx")
target = []
for path in os.listdir("target"):
    df = pd.read_excel(f"target/{path}", index_col=0)
    target.append(df)
df_target = pd.concat(target, axis=0)
dm = dm.merge(df_target, on=["Line","ProductNameEng", "Month", "Province"])
dm["has_stock"] = dm["StockVolume"]>= dm["province_target"]*2
dm.to_excel("sale_stock.xlsx",index=False)

In [62]:
dm

,Line,Month,ProductNameEng,Province,StockVolume,Province_coefficient,ratio,province_target,NetSalesVolumePack,has_stock
0,CNS,1,Ronopar 100/25,آذربایجان شرقی,795.0,0.043811,1.343461,16.375615,22,True
1,CNS,1,Ronopar 100/25,آذربایجان غربی,321.0,0.024339,1.099195,9.097564,10,True
2,CNS,1,Ronopar 100/25,اردبیل,696.0,0.015577,1.717493,5.822441,10,True
3,CNS,1,Ronopar 100/25,اصفهان,1471.0,0.073018,0.293119,27.292692,8,True
4,CNS,1,Ronopar 100/25,البرز,1100.0,0.030000,0.000000,11.213397,0,True
...,...,...,...,...,...,...,...,...,...,...
4673,General,8,Wellatrix 500,کردستان,750.0,0.009000,0.022011,817.790359,18,False
4674,General,8,Wellatrix 500,کرمان,2816.0,0.033000,0.429539,2998.564649,1288,False
4675,General,8,Wellatrix 500,گلستان,2255.0,0.019471,0.435203,1769.288367,770,False
4676,General,8,Wellatrix 500,گیلان,2262.0,0.029207,0.150720,2653.932550,400,False
4677,General,8,Wellatrix 500,یزد,4677.0,0.015577,0.408356,1415.430693,578,True