In [28]:
import pandas as pd
import numpy as np
import os
from datetime import datetime
df1 = pd.read_excel(r'C:\Users\Lenovo\Desktop\modaam\tasks\opl/commands_total.xlsx')
df2 = pd.read_excel(r'C:\Users\Lenovo\Desktop\modaam\tasks\opl/commands_total2.xlsx')
df = pd.concat([ df1, df2], ignore_index=True)

ing_prices= pd.read_excel(r'C:\Users\Lenovo\Desktop\modaam\tasks\opl/opl_kx_ingredients_prices.xlsx')

In [29]:
import pandas as pd
import logging

logging.basicConfig(level=logging.INFO)

# Define a function to extract ingredient_id and request_amount
def extract_info(request):
    try:
        # Canister info
        if request.startswith('canister:'):
            parts = request.split(':')[1].split(',')
            ingredient_id = int(parts[0])
            request_amount = int(parts[1])
            ingredient = 'canister'
            return pd.Series([ingredient_id, request_amount, ingredient])
        
        # Water
        elif request.startswith('water:'):
            parts = request.split(':')[1].split(',')
            ingredient_id = 35
            request_amount = int(parts[0])
            ingredient = 'water'
            return pd.Series([ingredient_id, request_amount, ingredient])
        
        # Espresso
        elif request.startswith('espresso:'):
            parts = request.split(':')[1].split(',')
            ingredient_id = 35
            request_amount = int(parts[1])
            ingredient = 'wateresp'
            return pd.Series([ingredient_id, request_amount, ingredient])
        
        # Syrup
        elif request.startswith('syrup:'):
            parts = request.split(':')[1].split(',')
            ingredient_id = int(parts[0]) + 1000
            request_amount = int(parts[1])
            ingredient = 'syrup'
            return pd.Series([ingredient_id, request_amount, ingredient])
        
        else:
            return pd.Series([None, None, None])
    
    except (IndexError, ValueError) as e:
        logging.info(f"Failed to parse request: {request} with error: {e}")
        return pd.Series([None, None, None])

# Apply the function to the request column and create new columns
df[['ingredient_id', 'request_amount', 'ingredient']] = df['request'].apply(extract_info)

INFO:root:Failed to parse request: syrup:,10,120000 with error: invalid literal for int() with base 10: ''
INFO:root:Failed to parse request: syrup:,10,120000 with error: invalid literal for int() with base 10: ''
INFO:root:Failed to parse request: syrup:,10,120000 with error: invalid literal for int() with base 10: ''

In [30]:
df

,request,response,created_at,name,created_at.1,ingredient_id,request_amount,ingredient
0,"serve:10000,18800,1000000,10000,1175,1133","200,15,1,""""",2024-06-15 10:55:46.000000,مپنا توسعه 2,2024-06-15 10:55:46.000000,NaN,NaN,None
1,"espresso:1,60,1,8000","200,3.0,3402,3058,62.4,2.2,83.5,13.9""""",2024-06-15 10:55:54.000000,هوایی مپنا,2024-06-15 10:55:54.000000,35.0,60.0,wateresp
2,cup:10000,"200,2,4565",2024-06-15 10:56:10.000000,مرکز تحقیقات سایپا,2024-06-15 10:56:10.000000,NaN,NaN,None
3,"spoon:1,10000",200,2024-06-15 10:56:12.000000,هوایی مپنا,2024-06-15 10:56:12.000000,NaN,NaN,None
4,cup:10000,"200,1,4756",2024-06-15 10:56:14.000000,مپنا توسعه 1,2024-06-15 10:56:14.000000,NaN,NaN,None
...,...,...,...,...,...,...,...,...
1818770,"water:80,1","200,3.5,86.5,82.2,5.7,10.3,""""",2024-06-15 10:55:11.000000,مپنا توسعه 2,2024-06-15 10:55:11.000000,35.0,80.0,water
1818771,"water:90,1","200,4.0,83.2,91.3,5.1,8.2,""""",2024-06-15 10:55:22.000000,هوایی مپنا,2024-06-15 10:55:22.000000,35.0,90.0,water
1818772,cup:10000,"200,1,2602",2024-06-15 10:55:31.000000,بیمه پارسیان، همکف,2024-06-15 10:55:31.000000,NaN,NaN,None
1818773,"espresso:1,60,1,8000","200,2.7,3604,3267,67.0,2.6,84.9,17.0""""",2024-06-15 10:55:39.000000,مپنا توسعه 2,2024-06-15 10:55:39.000000,35.0,60.0,wateresp
1818774,"canister:6,40,35000,2400,1","200,1,41.8,""""",2024-06-15 10:55:45.000000,بیمه پارسیان، همکف,2024-06-15 10:55:45.000000,6.0,40.0,canister

In [24]:

## old extracting request values

# Define a function to extract ingredient_id and request_amount
def extract_info(request):
    
    # ## canister info
    # if request.startswith('canister:'):
    #     parts = request.split(':')[1].split(',')
    #     ingredient_id = int(parts[0])
    #     request_amount = int(parts[1])
    #     ingredient = 'canister'
    #     return pd.Series([ingredient_id, request_amount, ingredient])

    # ##water
    # elif request.startswith('water:'):
    #     parts = request.split(':')[1].split(',')
    #     ingredient_id = 35
    #     request_amount = int(parts[0])
    #     ingredient = 'water'
    #     return pd.Series([ingredient_id, request_amount, ingredient])

    # #espresso
    # elif request.startswith('espresso:'):
    #     parts = request.split(':')[1].split(',')
    #     ingredient_id = 35
    #     request_amount = int(parts[1])
    #     ingredient = 'wateresp'
    #     return pd.Series([ingredient_id, request_amount, ingredient])
    
    ##syrup
    if request.startswith('syrup:'):
        parts = request.split(':')[1].split(',')
        ingredient_id = int(parts[0])+1000
        request_amount = int(parts[1])
        ingredient = 'syrup'
        return pd.Series([ingredient_id, request_amount, ingredient])
    else:
        return pd.Series([None, None])

    
# Apply the function to the request column and create new columns
df[['ingredient_id', 'request_amount' , 'ingredient']] = df['request'].apply(extract_info)

ValueError: invalid literal for int() with base 10: ''

In [17]:

# Define the set of ingredients to filter
ingredients_to_filter = {'syrup', 'wateresp', 'water', 'canister'}

# Filter the DataFrame
df = df[df['ingredient'].isin(ingredients_to_filter)]

In [18]:
# operation failed or not
parts = df['response'].str.split(',').str[0]

# Map the parts to the corresponding operation
df['operation'] = parts.map({'500': 0, '200': 1})

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_320\794882304.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['operation'] = parts.map({'500': 0, '200': 1})

In [5]:
## drop coulmns

column_to_drop = 'created_at.1'
df.drop(columns=[column_to_drop], inplace=True)

In [6]:
## syrup id mapping
def translate_syrup_id(ingredient_id): 
    translation_dict = {
        1001: 47, 
        1002: 44,
        1003: 45, 
        1004: 43
    }
    return translation_dict.get(ingredient_id, ingredient_id)


df['ingredient_id'] = df['ingredient_id'].apply(translate_syrup_id)

In [7]:
## exclude topping canister
def topping(request):
    if request.startswith('canister:'):
        partw = request.split(':')[1].split(',')
        topping = 1 - (int(partw[4]))
        return topping
        
    else:
        return 50
df['topping'] = df['request'].apply(topping)

## 50 : no canister , 1 : topping , 0: no topping( based on mass) ( i consider a not in code so its vice versa with mass1/time0)
topping_to_filter = {50,0}

# Filter the DataFrame
df = df[df['topping'].isin(topping_to_filter)]

In [30]:
# ### solving the response problem 



# ## df['ingredient'] = df['ingredient'].astype(str, errors='ignore')

# # Define a function to extract ingredient_id and request_amount
# def extract_info(response,ingredient):
    
#     ## canister info
#     if ingredient == 'canister':
#         response_amount = response.str.split(',').str[2]
#         return response_amount
#     ## water info
#     if ingredient == 'water':
#         response_amount = response.str.split(',').str[3]

#     else:
#         return None

    
# # Apply the function to the request column and create new columns
# df['response_amount'] = df[['response','ingredient']].apply(extract_info)

In [17]:
canister_df = df[df['ingredient'] == 'canister']
# Split the 'response' column by commas and extract the fourth element
canister_df['response_amount'] = canister_df['response'].str.split(',').str[2]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4364\2696585384.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  canister_df['response_amount'] = canister_df['response'].str.split(',').str[2]

In [18]:
water_df = df[df['ingredient'] == 'water']
# Split the 'response' column by commas and extract the fourth element
water_df['response_amount'] = water_df['response'].str.split(',').str[3]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4364\2777162387.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  water_df['response_amount'] = water_df['response'].str.split(',').str[3]

In [ ]:
wateresp_df = df[df['ingredient'] == 'wateresp']
# Split the 'response' column by commas and extract the fourth element
wateresp_df['response_amount'] = wateresp_df['response'].str.split(',').str[4]

In [ ]:
syrup_df = df[df['ingredient'] == 'syrup']
# Split the 'response' column by commas and extract the fourth element
syrup_df['response_amount'] = syrup_df['response'].str.split(',').str[2]

In [19]:
result_df = pd.concat([ canister_df, water_df], ignore_index=True)

In [27]:
## merge with ing_price


# Ensure ingredient_id columns are of the same data type (e.g., integers)
result_df['ingredient_id'] = result_df['ingredient_id'].astype(int, errors='ignore')
ing_prices['ingredient_id'] = ing_prices['ingredient_id'].astype(int, errors='ignore')

# Perform the merge
merged_df = pd.merge(result_df, ing_prices, on='ingredient_id', how='left')

# Display the merged DataFrame
#merged_df.to_excel('merged.xlsx')

In [28]:
## overpourni loss computation

# Check and convert columns to numeric if needed
merged_df['response_amount'] = pd.to_numeric(merged_df['response_amount'], errors='coerce')
merged_df['request_amount'] = pd.to_numeric(merged_df['request_amount'], errors='coerce')

# Calculate 'loss price' based on conditions using np.where
condition = (merged_df['operation'] == 1) & ((merged_df['response_amount'] - merged_df['request_amount']) > 0)
merged_df['loss price'] = np.where(condition,
                                   ((merged_df['response_amount'] - merged_df['request_amount']) / merged_df['amount']) * merged_df['price'] * 1.1,
                                   0)

In [30]:
## merge with ing_name 

merged_df['created_at_x'] = pd.to_datetime(merged_df['created_at_x'])

# Extract month and year for grouping
merged_df['month_year'] = merged_df['created_at_x'].dt.to_period('M')
ingredients = pd.read_excel(r'C:\Users\Lenovo\Desktop\modaam\tasks\opl/kx_ingredients.xlsx')

# Ensure ingredient_id columns are of the same data type (e.g., integers)
merged_df['ingredient_id'] = merged_df['ingredient_id'].astype(int, errors='ignore')
ingredients['ingredient_id'] = ingredients['ingredient_id'].astype(int, errors='ignore')

# Perform the merge
merged_df_ingname = pd.merge(merged_df, ingredients, on='ingredient_id', how='left')

merged_df_ingname.to_excel('overpouring_loss_total.xlsx')

In [ ]:
# figure it out 2

## extract response all in once

# Define a function to extract response_amount
def extract_response_info(ingredient,response):
    
    ## canister info
    if ingredient=='canister':
        parts = response.split(',')
        
        response_amount = int(parts[2])
        
        return response_amount

    # ##water
    # elif request.startswith('water:'):
    #     parts = response.split(':')[1].split(',')
    #     ingredient_id = 35
    #     request_amount = int(parts[0])
    #     ingredient = 'water'
    #     return pd.Series([ingredient_id, request_amount, ingredient])

    # #espresso
    # elif request.startswith('espresso:'):
    #     parts = response.split(':')[1].split(',')
    #     ingredient_id = 35
    #     request_amount = int(parts[1])
    #     ingredient = 'wateresp'
    #     return pd.Series([ingredient_id, request_amount, ingredient])
    
    # ##syrup
    # elif request.startswith('syrup:'):
    #     parts = response.split(':')[1].split(',')
    #     ingredient_id = int(parts[0])+100
    #     request_amount = int(parts[1])
    #     ingredient = 'syrup'
    #     return pd.Series([ingredient_id, request_amount, ingredient])
    else:
        return None

    
# Apply the function to the request column and create new columns
df[['response_amount']] = df[['ingredient','response']].apply(extract_response_info)